
package com.ws.soap.getproductsws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAllProducts", targetNamespace = "http://getProductsWs.soap.ws.com/", wsdlLocation = "http://user-pc:8080/GovernmentSupplyWebProject/GetAllProducts?wsdl")
public class GetAllProducts_Service
    extends Service
{

    private final static URL GETALLPRODUCTS_WSDL_LOCATION;
    private final static WebServiceException GETALLPRODUCTS_EXCEPTION;
    private final static QName GETALLPRODUCTS_QNAME = new QName("http://getProductsWs.soap.ws.com/", "GetAllProducts");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://user-pc:8080/GovernmentSupplyWebProject/GetAllProducts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETALLPRODUCTS_WSDL_LOCATION = url;
        GETALLPRODUCTS_EXCEPTION = e;
    }

    public GetAllProducts_Service() {
        super(__getWsdlLocation(), GETALLPRODUCTS_QNAME);
    }

    public GetAllProducts_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETALLPRODUCTS_QNAME, features);
    }

    public GetAllProducts_Service(URL wsdlLocation) {
        super(wsdlLocation, GETALLPRODUCTS_QNAME);
    }

    public GetAllProducts_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETALLPRODUCTS_QNAME, features);
    }

    public GetAllProducts_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAllProducts_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAllProducts
     */
    @WebEndpoint(name = "newPort")
    public GetAllProducts getNewPort() {
        return super.getPort(new QName("http://getProductsWs.soap.ws.com/", "newPort"), GetAllProducts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAllProducts
     */
    @WebEndpoint(name = "newPort")
    public GetAllProducts getNewPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://getProductsWs.soap.ws.com/", "newPort"), GetAllProducts.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETALLPRODUCTS_EXCEPTION!= null) {
            throw GETALLPRODUCTS_EXCEPTION;
        }
        return GETALLPRODUCTS_WSDL_LOCATION;
    }

}
